SETTINGS:
  XP_1: #Name of reward
    CHANCE: 80 #Chance to get command
    TYPE: COMMAND #Type: COMMAND, MYTHICMOB, MMOITEMS
    DISPLAY: "&a5 XP" #Display: Only for command type
    ID: "eco add %player_name% 5" #Command
  QUAIVATBIEN: #Name of reward
    CHANCE: 10 #Chance to get mob
    TYPE: MYTHICMOB #Type: COMMAND, MYTHICMOB, MMOITEMS
    ID: QUAIVATBIEN #InternalName of mob
  SACHPHUPHEP1: #Name of reward
    CHANCE: 1 #Chance to get item
    TYPE: MMOITEMS #Type: COMMAND, MYTHICMOB, MMOITEMS
    ID: MATERIAL;SACHPHUPHEP1 #TYPE;ID of item
  XP_2:
    CHANCE: 70
    TYPE: COMMAND
    DISPLAY: "&a10 XP"
    ID: "bcore xp add %player_name% 10"
  XP_3:
    CHANCE: 60
    TYPE: COMMAND
    DISPLAY: "&a15 XP"
    ID: "bcore xp add %player_name% 15"
  XP_4:
    CHANCE: 50
    TYPE: COMMAND
    DISPLAY: "&a20 XP"
    ID: "bcore xp add %player_name% 20"
  XP_5:
    CHANCE: 40
    TYPE: COMMAND
    DISPLAY: "&a30 XP"
    ID: "bcore xp add %player_name% 30"
  QP_1:
    CHANCE: 20
    TYPE: COMMAND
    DISPLAY: "&a20 XP"
    ID: "bcore qp add %player_name% 10"