FISHING_MODE:
  COMMAND:
    DISABLE_VANILLA_FISH: true
  MMOITEMS:
    DISABLE_VANILLA_FISH: true
  MYTHICMOB:
    DISABLE_VANILLA_FISH: true
  CUSTOM_FISH:
    ENABLE: true
    DISABLE_VANILLA_FISH: true
SETTINGS:
  PREFIX:
    ENABLE: true
    PREFIX: "&7[ &bLiteFishing&7 ]"
SELL:
  COMMAND: #You can add more command, all command below this will execute when player sell fish
    - "eco give %player_name% <cost>"