FISHING_MODE:
  COMMAND:
    DISABLE_VANILLA_FISH: true
  MMOITEMS:
    DISABLE_VANILLA_FISH: true
  MYTHICMOB:
    DISABLE_VANILLA_FISH: true
  CUSTOM_FISH:
    ENABLE: true
    DISABLE_VANILLA_FISH: true